"""
Environment variable and .toml config file key constants.
"""

# Env-Var Name Constants
FLASK_DEBUG_ENV_VAR = "FLASK_DEBUG"
FLASK_KEY_ENV_VAR = "FLASK_SECRET_KEY"
OBJ_STORE_ENDPOINT_ENV_VAR = "OBJECT_STORAGE_ENDPOINT"
OBJ_STORE_ACCESS_KEY_ENV_VAR = "OBJECT_STORAGE_ACCESS_KEY"
OBJ_STORE_SECRET_KEY_ENV_VAR = "OBJECT_STORAGE_SECRET_KEY"
OBJ_STORE_SECURE_ENV_VAR = "OBJECT_STORAGE_SECURE"
LOGGER_LEVEL_ENV_VAR = "LOGGER_LEVEL"

# Config File Key Constants
FLASK_TABLE = "flask"
FLASK_DEBUG = "debug"
FLASK_KEY = "secret_key"
OBJ_STORE_TABLE = "object_storage"
OBJ_STORE_ENDPOINT = "endpoint"
OBJ_STORE_ACCESS_KEY = "access_key"
OBJ_STORE_SECRET_KEY = "secret_key"
OBJ_STORE_SECURE = "secure"
LOGGER_TABLE = "logger"
LOGGER_LEVEL = "level"

